dataset:
  path_pattern: /home/ayu/datasets/jvs_preprocessed/jvs-train-{000000..000999}.tar.gz
  shuffle: 1000          # wds shuffle size
batch_size: 8            # Adapter 用
epochs: 5
optim:
  lr: 2.0e-4
  weight_decay: 0.01
save_dir: exp/adapter
