preprocess:
  preprocess_dataset:
    _target_: miipher_2.dataset.fleurs_r.FleursRCorpus
    datasets:
      -
        _target_: miipher_2.dataset.fleurs_r.FleursRCorpus
        root: /home/ayu/datasets/fleurs-r/
    root: /home/ayu/datasets/fleurs-r/
  degradation:
    format_encoding_pairs:
      - format: mp3
        compression: 16
      - format: mp3
        compression: 32
      - format: mp3
        compression: 64
      - format: mp3
        compression: 128
      - format: ogg
        compression: -1
      - format: ogg
        compression: 0
      - format: ogg
        compression: 1
      - format: wav
        encoding: ALAW
        bits_per_sample: 8
    reverb_conditions:
      p: 0.5
      reverbation_times:
        max: 0.5
        min: 0.2
      room_xy:
        max: 10.0
        min: 2.0
      room_z:
        max: 5.0
        min: 2.0
      room_params:
        fs: 22050
        max_order: 10
        absorption: 0.2
      source_pos:
        - 1.0
        - 1.0
        - 1.0
      mic_pos:
        - 1.0
        - 0.7
        - 1.2
    n_rirs: 1000
    background_noise:
      snr:
        max: 30.0
        min: 5.0
      patterns:
        -
          - /home/audio/TAU2023/dataset/TAU-urban-acoustic-scenes-2022-mobile-development/audio/
          - '**/*.wav'
        -
          - /home/audio/TAU2021/datasets/TAU-urban-acoustic-scenes-2020-mobile-development/audio/
          - '**/*.wav'
  train_tar_sink:
    _target_: webdataset.ShardWriter
    pattern: /home/ayu/datasets/fleurs-r_preprocessed/fleurs-r-train-%06d.tar.gz
  val_tar_sink:
    _target_: webdataset.ShardWriter
    pattern: /home/ayu/datasets/fleurs-r_preprocessed/fleurs-r-val-%06d.tar.gz
  val_size: 600
  n_repeats: 4
  feature_cache_dir: /home/ayu/datasets/hubert_cache/fleurs_r_corpus
sampling_rate: 22050

