# --- 一括処理の基本設定 ---
input_dir: "/home/ayu/GitHub/miipher-plaoground/degrade_samples" # PA_E3, samples_8khz_16khz, degrade_samples
output_dir: "/home/ayu/GitHub/miipher-plaoground/hubert_large_l2/degrade_samples"

# 処理対象とする音声ファイルの拡張子リスト
extensions:
  - ".wav"

# --- 推論の基本設定 ---
device: "cuda" # "cuda" または "cpu"

# --- チェックポイントのパス ---
# Adapter学習で生成された最終モデル
adapter_ckpt: "/home/ayu/GitHub/open-miipher-2/exp/adapter_l2/checkpoint_199k.pt"

vocoder_ckpt: /home/ayu/GitHub/ssl-vocoders/tb_logs/lightning_logs/version_22/checkpoints/epoch=240-step=445008.ckpt


# --- モデル設定 (Fine-tuning時と一致させる) ---
model:
  hubert_model_name: "rinna/japanese-hubert-large"
  hubert_layer: 2
  adapter_hidden_dim: 1024


# --- 出力設定 ---
output_sampling_rate: 22050
