# --- 一括処理の基本設定 ---
input_dir: "/home/ayu/GitHub/miipher-plaoground/samples_8khz"   # 音声ファイルが入っているディレクトリ
output_dir: "/home/ayu/GitHub/miipher-plaoground/8khz_miipher2" # 修復後の音声を出力するディレクトリ

# 処理対象とする音声ファイルの拡張子リスト
extensions:
  - ".wav"

# --- 推論の基本設定 ---
device: "cuda" # "cuda" または "cpu"

# --- チェックポイントのパス ---
# Adapter学習で生成された最終モデル
adapter_ckpt: "exp/adapter_l7/checkpoint_197k.pt"

# HiFi-GAN Fine-tuningで生成されたチェックポイント
vocoder_ckpt: "exp/hifigan_pretrain_layer_6_mhubert_147/checkpoint_98k.pt"


# --- モデル設定 (Fine-tuning時と一致させる) ---
model:
  hubert_model_name: "utter-project/mHuBERT-147"
  hubert_layer: 6
  adapter_hidden_dim: 768

# --- Vocoder設定 ---
# Prenetのパラメータ (hifigan.pyの実装に合わせる)
prenet:
  in_dim: 768     # HuBERTの出力次元数と一致
  n_layers: 4
  mel_dim: 80
  src_fps: 50.0
  tgt_hop: 256
  sr: 22050

# Generatorのconfigはvocoder_ckptと同じディレクトリのconfig.jsonから自動で読み込まれます

# --- 出力設定 ---
output_sampling_rate: 22050
