# --- 推論の基本設定 ---
input_wav: "samples/sample.wav"
output_wav: "samples/miipher2.wav"
device: "cuda" # "cuda" または "cpu"

# --- チェックポイントのパス ---
# Adapter学習で生成された最終モデル
adapter_ckpt: "exp/adapter_layer_6_mhubert_147/checkpoint_199k.pt"

# Lightning SSL-Vocoderで学習されたチェックポイント (.ckpt形式)
# ssl-vocodersリポジトリで学習したモデルのパスを指定してください
vocoder_ckpt: "/home/ayu/GitHub/ssl-vocoders/epoch=49-step=882200.ckpt"

model:
  hubert_model_name: "utter-project/mHuBERT-147"
  hubert_layer: 6
  adapter_hidden_dim: 768



# --- 出力設定 ---
output_sampling_rate: 22050
