# Miipher-2 Inference Configuration

# Input/Output paths
input_audio: /path/to/noisy_audio.wav
output_audio: /path/to/clean_audio.wav
reference_audio: null  # Optional: for computing metrics

# Model configuration
checkpoint: /path/to/final_model.pt  # Trained model checkpoint
device: "cuda"
sample_rate: 16000

# Processing configuration
chunk_length: 10.0      # seconds (for long audio processing)
overlap_length: 0.5     # seconds (overlap between chunks)

# Metrics computation
compute_metrics: false   # Set to true if reference_audio is provided

# Hydra configuration
hydra:
  run:
    dir: ./outputs/inference/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
