# --- 一括処理の基本設定 ---
input_dir: "/home/ayu/GitHub/miipher-plaoground/PA_E3"   # 音声ファイルが入っているディレクトリ
output_dir: "/home/ayu/GitHub/miipher-plaoground/PA_E3" # 修復後の音声を出力するディレクトリ

# 処理対象とする音声ファイルの拡張子リスト
extensions:
  - ".wav"

# --- 推論の基本設定 ---
device: "cuda" # "cuda" または "cpu"

# --- チェックポイントのパス ---
# Adapter学習で生成された最終モデル
adapter_ckpt: "exp/adapter_layer_6_mhubert_147/checkpoint_199k.pt"

# Lightning SSL-Vocoderで学習されたチェックポイント (.ckpt形式)
# ssl-vocodersリポジトリで学習したモデルのパスを指定してください
vocoder_ckpt: "/home/ayu/GitHub/ssl-vocoders/epoch=45-step=810824.ckpt"


# --- モデル設定 (Fine-tuning時と一致させる) ---
model:
  hubert_model_name: "utter-project/mHuBERT-147"
  hubert_layer: 6
  adapter_hidden_dim: 768


# --- 出力設定 ---
output_sampling_rate: 22050
