input_wav: "samples/sample.wav"
output_wav: "samples/miipher2_p.wav"
device: "cuda"


adapter_ckpt: "/home/ayu/GitHub/open-miipher-2/exp/adapter_layer_6_mhubert_147/checkpoint_199k_fixed.pt"

vocoder_ckpt: /home/ayu/GitHub/ssl-vocoders/tb_logs/lightning_logs/version_12/checkpoints/epoch=58-step=1042796.ckpt

model:
  hubert_model_name: "utter-project/mHuBERT-147"
  hubert_layer: 6
  adapter_hidden_dim: 768


# --- 出力設定 ---
output_sampling_rate: 22050
