# --- 一括処理の基本設定 ---
input_dir: "/home/ayu/GitHub/miipher-plaoground/PA_E3" # PA_E3, samples_8khz_16khz, degrade_samples
output_dir: "/home/ayu/GitHub/miipher-plaoground/wavlm_base_l2/PA_E3"

# 処理対象とする音声ファイルの拡張子リスト
extensions:
  - ".wav"

# --- 推論の基本設定 ---
device: "cuda" # "cuda" または "cpu"

# --- チェックポイントのパス ---
# Adapter学習で生成された最終モデル
adapter_ckpt: "/home/ayu/GitHub/open-miipher-2/exp/wavlm_base_l2/checkpoint_199k.pt"

vocoder_ckpt: /home/ayu/GitHub/ssl-vocoders/tb_logs/lightning_logs/version_28/checkpoints/epoch=219-step=404920.ckpt


# --- モデル設定 (Fine-tuning時と一致させる) ---
model:
  hubert_model_name: "microsoft/wavlm-base"
  hubert_layer: 2
  adapter_hidden_dim: 768


# --- 出力設定 ---
output_sampling_rate: 22050
