trainer:
  _target_: lightning.Trainer
  accelerator: "gpu"
  devices: [0]
  precision: 32
  check_val_every_n_epoch: 1
  max_epochs: 33000

ckpt_path:

loggers:
  - _target_: lightning.pytorch.loggers.TensorBoardLogger
    save_dir: "tb_logs"
  - _target_: lightning.pytorch.loggers.WandbLogger
    project: "hifigan-lightning"
    log_model: "all"
